---
server:
  port: 9000
spring:
  application:
    name: discovery-service
  profiles: peer1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/

---
server:
  port: 9001
spring:
  application:
    name: discovery-service
  profiles: peer2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:9002/eureka/

---
server:
  port: 9002
spring:
  application:
    name: discovery-service
  profiles: peer3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:9001/eureka/